# Generated by Django 4.1.4 on 2022-12-21 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0002_profile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-updated_at", "-created_at"]},
        ),
        migrations.AlterModelManagers(
            name="profile",
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="about_me",
            field=models.TextField(
                default="say something about yourself...", verbose_name="About Me"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Nairobi", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="KE", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="deleted",
            field=models.BooleanField(
                default=True, help_text="This is for soft delete", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="license",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Real Estate license"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="num_reviews",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Number of Reviews"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+254745678910",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="/profile_default.png",
                upload_to="",
                verbose_name="Profile Photo",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
