# Generated by Django 4.1.4 on 2023-01-06 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_active",
        ),
    ]
