# Generated by Django 4.1.4 on 2023-01-07 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_options_alter_profile_managers_and_more"),
        ("ratings", "0002_alter_rating_managers_remove_rating_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_review",
                to="profiles.profile",
                verbose_name="Agent being rated",
            ),
        ),
    ]
