# Generated by Django 4.1.4 on 2023-01-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_created_at_alter_user_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deleted",
            field=models.BooleanField(
                default=False, help_text="This is for soft delete", null=True
            ),
        ),
    ]
