# Generated by Django 4.1.4 on 2023-01-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="deleted",
            field=models.BooleanField(
                default=False, help_text="This is for soft delete", null=True
            ),
        ),
        migrations.AlterField(
            model_name="propertyviews",
            name="deleted",
            field=models.BooleanField(
                default=False, help_text="This is for soft delete", null=True
            ),
        ),
    ]
