# Generated by Django 4.1.4 on 2023-02-11 06:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_newproject_newprojectviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newproject",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
