# Generated by Django 4.1.4 on 2023-02-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_newproject_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="newproject",
            name="published_status",
            field=models.BooleanField(default=False, verbose_name="Published Status"),
        ),
    ]
