# Generated by Django 4.1.4 on 2023-02-21 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("properties", "0005_newproject_published_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newprojectviews",
            name="new_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="NewProject",
                to="properties.newproject",
            ),
        ),
        migrations.AlterField(
            model_name="propertyviews",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Property",
                to="properties.property",
            ),
        ),
        migrations.CreateModel(
            name="PropertyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "deleted",
                    models.BooleanField(
                        default=False, help_text="This is for soft delete", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.agent"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "abstract": False,
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
    ]
