# Generated by Django 4.1.4 on 2023-02-27 02:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_alter_newprojectviews_new_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylisting",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Total Views"),
        ),
        migrations.CreateModel(
            name="PropertyListingViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "deleted",
                    models.BooleanField(
                        default=False, help_text="This is for soft delete", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("ip", models.CharField(max_length=250, verbose_name="IP Address")),
                (
                    "property_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PropertyListing",
                        to="properties.propertylisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Total Views on Property Listing",
                "verbose_name_plural": "Total Property Listing Views",
            },
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
    ]
